### PR TITLE
Add min-width breakpoints support 

### PR DESCRIPTION
**Pull request by youedd**
Hello 👋

As mentioned in #50 having breakpoints support in tailwind-rn will be a big plus especially for projects with shared code between web and mobile.

This PR adds support for min-width breakpoints using hooks.
There is no breaking changes. if the hook is not used the breakpoints styles are ignored.
```javascript
import tailwind from 'tailwind-rn';
...
const Comp = () => (
    <Text style={tailwind('text-blue-800 md:font-semibold')}> // breakpoint ignored
        Hello Tailwind
    </Text>
);
```
```javascript
import {useTailwind} from 'tailwind-rn';
...
const Comp = () => {
    const {tailwind} = useTailwind();
...
    <Text style={tailwind('text-blue-800 md:font-semibold')}> // breakpoints styles applied
        Hello Tailwind
    </Text>
```
It supports custom configuration aswell with createHook helper,

There's also an example for react-native-web 
demo

It's not a final version yet, there will be some improvements to do:

- [x] Avoid reading from tailwind.config.js file and try to get the configuration directly from Tailwind if possible

- [x] Add memoization for better performance

- [x] Support font variant numeric with breakpoints

Let me know if you see more improvements to do and feel free to commit and change anything if you want.

### CODE REVIEW

**Comment by youedd** [comment]
Since React Native fontVariant style is an array of enum, supporting font variant numeric and min-width breakpoints is a bit tricky.

```javascript 
// Example::
tailwind('oldstyle-nums sm:lining-nums md:tabular-nums');

// For md screens : should it take into consideration sm et default rules 
{ fontVariant; ['oldstyle-nums', 'lining-nums' , 'tabular-nums'] };
// Or override them
{ fontVariant; ['tabular-nums'] };

//For lg/xl/2xl  which are not defined, should it be on of the md possibilities ?
{ fontVariant; ['oldstyle-nums', 'lining-nums' , 'tabular-nums'] };
{ fontVariant; ['tabular-nums'] };
// Or should it return a blank rule
{ };
```
In this PR I chose ⬇️ 
```javascript 
// Example::
tailwind('oldstyle-nums sm:lining-nums md:tabular-nums');
// sm
{ fontVariant; ['lining-nums'] };
// md /lg/xl/2xl 
{ fontVariant; ['tabular-nums'] };

```
But am not sure if it's the right thing to do.

**Comment by smlarkin** [comment]
@youedd Awesome!!!

Does this follow the TW sizing... https://tailwindcss.com/docs/responsive-design ?

@vadimdemedes I'lll buy you a beer if you can review this ... really :)

**Comment by youedd** [comment]
@smlarkin, Yes it follows the TW configuration, and supports basic customization too https://tailwindcss.com/docs/breakpoints

**Comment by smlarkin** [comment]
> @smlarkin, Yes it follows the TW configuration, and supports basic customization too https://tailwindcss.com/docs/breakpoints

@youedd Very Nice!

**Comment by danlordan** [comment]
Hi - loving tailwind-rn so far. Ts there a timetable for this PR being merged? Trying to decide whether to try the solution mentioned [here](https://github.com/vadimdemedes/tailwind-rn/issues/50) or wait for this to be merged.

**Comment by renatodex** [comment]
@vadimdemedes , do you need help reviewing this?

Besides the example folder, and a small refactor in the `index.js`, the PR seems pretty straightforward.
Is this not approved yet because there are other concerns?

Let's push this!

**Comment by danlordan** [comment]
@vadimdemedes I can help if you need anything, but would love to see this pushed in!

**Comment by teovillanueva** [comment]
This is awesome! Will this be included in the next release? 🚀

**Comment by vadimdemedes** [comment]
Sorry everyone for the delay!

I'm working on the major new release in `v4` branch, which is going to include support for media queries and dark mode too.

@youedd Thank you for the effort you've put in here, but unfortunately I have to close this PR, because `v4` branch is going to solve this problem a little differently. Sorry!

**Comment by vadimdemedes** [comment]
Hi folks, dropping by to let you know that full support for responsive design, dark mode and more is now released in [v4.0.0](https://github.com/vadimdemedes/tailwind-rn/releases/tag/v4.0.0)!

**Comment by deanmraz** [comment]
@vadimdemedes great work will check this out!

**Pull request closed without merging**
