### PR TITLE
Fix #16: allow generating custom background colors

### LINKED ISSUE #16: Support custom Tailwind config
I created custom config with colors like `grey-900` but they where removed from styles.json.
I found this line in build.js `/^bg-(transparent|black|white|gray|red|orange|yellow|green|teal|blue|indigo|purple|pink)/`
I think it should be like this `/^bg-/`

### PR DESCRIPTION
**Pull request by karolsw3**
Custom background colors are not generated in styles.json. This PR fixes that.

### CODE REVIEW

**Comment by vadimdemedes** [comment]
See https://github.com/vadimdemedes/tailwind-rn/issues/16#issuecomment-639508920.

**Comment by vmarcel** [comment]
Can this be merged, please?

**Comment by TylerOlthuizen** [comment]
> Can this be merged, please?

xD please?

**Comment by vadimdemedes** [comment]
See the link I posted above, there's no proper solution to this problem yet.

**Pull request closed without merging**
