### PR TITLE
Adds opacity support to getColor()

### PR DESCRIPTION
**Pull request by eduludi**
This allows to provide an `opacity-*` class to `getColor()`.

Example:

```js
getColor('blue-500 opacity-50') // => 'rgba(66, 153, 225, 0.5)'
```

Also:
* Adds test
* Updates `readme.md`

### CODE REVIEW

**Comment by vadimdemedes** [comment]
Thanks for this PR. Could you add `opacity` as a second argument to `getColor`?

```js
getColor('blue-500', {opacity: 0.5})
```

Make sure to also add validation to ensure that only supported values by Tailwind are accepted (e.g. `0`, `0.25`, `0.5`, ...).

**Comment by eduludi** [comment]
@vadimdemedes IMO how it is set in the PR makes sense: It follows tailwind's naming convention and ergonomics.

**Comment by vadimdemedes** [comment]
Disagree, because the argument of `getColor` is the name of the color in the palette, not a set of Tailwind classes.

**Comment by cevr** [comment]
I think the api @eduludi is more resilient to change (in the case tailwind adds more color utilities). Instead of having to type check a potentially infinitely growing list of props , this works without any overhead

**Comment by vadimdemedes** [comment]
I obviously can't predict the future, but I don't think there will be a lot more props to configure the color. What else can be applied to color besides opacity to change the output?

**Comment by cevr** [comment]
> I obviously can't predict the future, but I don't think there will be a lot more props to configure the color. What else can be applied to color besides opacity to change the output?

Perhaps more granular opacity control , or perhaps they may offer some utility that augmented the color based on contrast ratios 

 In general the library delegates the transformations to be done by tailwind itself , so it would make sense that this function also delegates it to tailwind instead of manually applying it. 

What do you think @vadimdemedes ?

**Comment by vadimdemedes** [comment]
I had second thoughts about this and I now agree that `opacity-50` is a better option. Particularly because of custom configs, if you add a custom opacity class, it will be picked up automatically by this library.

**Comment by vadimdemedes** [comment]
@eduludi Could you fix merge conflict and link to https://tailwindcss.com/docs/background-opacity in readme to let people know which `opacity-*` classes are available?

**Comment by eduludi** [comment]
@vadimdemedes let me know if that is enough. Thanks (and sorry for the delay).

**Comment by vadimdemedes** [comment]
Thank you!

**Pull request merged**
