### PR TITLE
Return empty object when no class names are passed

### PR DESCRIPTION
**Pull request by xiCO2k**
To support cases like this:

`tailwind(checkSomeVar && 'text-green-500')`

### CODE REVIEW

**Comment by vadimdemedes** [comment]
I think you should do it the other way instead: `checkSomeVar && tailwind('text-green-500')`. Also, there's another option:

```js
tailwind(classNames({
  'text-green-500': checkSomeVar
}));
```

**Comment by xiCO2k** [comment]
Yes there is a bunch of workarounds, but I thought it was good to basically ignore when its empty. since most o the packages do the same.

**Comment by vadimdemedes** [comment]
Now that I think of it, if `classNames` returns an empty string, we need to handle that case. Thanks!

**Comment by vadimdemedes** [comment]
Released in `1.0.1`.

**Comment by xiCO2k** [comment]
Awsome

**Pull request merged**
